### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Basielienis** [arjan/mod_rsc_name#4]
I want to use [Sourcegraph](https://sourcegraph.com) for mod_rsc_name code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/arjan/mod_rsc_name. (It should only take 30 seconds.)

Thank you!

**Comment by arjan** [comment]
why did you close this issue?

**Comment by Basielienis** [comment]
I'm not an author of this issue. Looks like some github bug. Have been using Thor for github access for a month cause of mad soviet censorship, guess this could trigger some bug. Have to report as a security problem maybe.
